### ISSUE TITLE
Error in kubeflow 05_04_Pipeline_SageMaker

### ISSUE THREAD

**Issue by Jeffwan** [aws-samples/eks-workshop#521]
```
Transform job ended with status: Completed
    s3_client.download_file(bucket, output_key, 'valid-result')
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
Runtime execution graph. Only steps that are currently running or have already completed are shown.

```

![image](https://user-images.githubusercontent.com/4739316/69012632-cc5bca00-092c-11ea-9b9e-7bb249a830c4.png)

**Comment by Jeffwan** [comment]
My original execution role has SM and follow policies.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}

```

**Comment by dalbhanj** [comment]
@Jeffwan we need to investigate why its still failing. The chapter has an IAM policy with full S3 permissions. Also, the transform job completes. I'm not sure what this error mean

**Comment by Jeffwan** [comment]
This is an error from batch_transormation component. It tried to fetch result file after job finish. I will double check images and code to figure out the issue.

```
WARNING:root:pandas failed to import. Analytics features will be impaired or broken.
INFO:botocore.credentials:Found credentials in environment variables.
INFO:root:Submitting Batch Transformation request to SageMaker...
INFO:root:Batch Job request submitted. Waiting for completion...
Traceback (most recent call last):
('Created Transform job with name: ', 'BatchTransform-20191202005620-C12M')
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job ended with status: Completed
  File "batch_transform.py", line 48, in <module>
    main()
  File "batch_transform.py", line 39, in main
    _utils.print_tranformation_job_result(args.output_location)
  File "/app/common/_utils.py", line 219, in print_tranformation_job_result
    s3_client.download_file(bucket, output_key, 'valid-result')
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```
