### ISSUE TITLE
Inference module is failing with ConnectionError

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/eks-workshop#565]
Tried to run the Kubeflow inference module following the instructions at https://eksworkshop.com/advanced/420_kubeflow/inference/.

Got the following error:

```
TeamRole:~/environment $ python inference_client.py --endpoint http://localhost:8500/v1/models/mnist:predict
Data: {"signature_name": "serving_default", "instances": ...  [0.0], [0.0], [0.0], [0.0], [0.0], [0.0], [0.0]]]]}
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_client.py", line 51, in <module>
    main()
  File "inference_client.py", line 43, in main
    json_response = requests.post(args.endpoint, data=data, headers=headers)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

Server-side logs:

```
E1127 03:58:13.925811   11618 portforward.go:400] an error occurred forwarding 8500 -> 8500: error forwarding port 8500 to pod e415434b6e39f477b033438e91e66dff31a585195cf256fd1313bdf09449daaa, uid : exit status 1: 2019/11/27 03:58:13 socat[21380] E connect(5, AF=2 127.0.0.1:8500, 16): Connection refused
```

**Comment by arun-gupta** [comment]
Inference pod was running fine:

```
TeamRole:~/environment/eksworkshop-eksctl $ kubectl get pods -l app=mnist,type=inference
NAME                               READY   STATUS    RESTARTS   AGE
mnist-inference-584c589c68-9gzjp   1/1     Running   0          17s
```

Terminated port forward and started it again, and now it seems to be working:

```
TeamRole:~/environment $ python inference_client.py --endpoint http://localhost:8500/v1/models/mnist:predict
Data: {"signature_name": "serving_default", "instances": ... 4901960784], [0.13333333333333333], [0.0], [0.0]]]]}
The model thought this was a Ankle boot (class 9), and it was actually a Ankle boot (class 9)
```

Is there some additional check/wait required for the first experience to work?

**Comment by Jeffwan** [comment]
Seems like a problem on the port-forward? Let's attach serving pods logs if we see this issue again.

**Comment by dalbhanj** [comment]
Maybe we shouldn't put port-forward in the background? Did you follow this instruction and still hit the issue? "Leave the current terminal running and open new terminal for installing tensorflow"

**Comment by arun-gupta** [comment]
Running in background indeed turns out to be the issue. Will send a PR to fix this.
