### ISSUE TITLE
error running mnist-training

### ISSUE THREAD

**Issue by ialek36** [aws-samples/eks-workshop#597]
@dalbhanj 
@Jeffwan 
@arun-gupta 

Going through these steps in Oregon (us-west-2), the last step fails to train.  The log is below.
https://eksworkshop.com/prerequisites
https://eksworkshop.com/eksctl
https://eksworkshop.com/kubeflow/install/
https://eksworkshop.com/kubeflow/dashboard/
https://eksworkshop.com/kubeflow/jupyter/
https://eksworkshop.com/kubeflow/training/

workshop:~/environment/eksworkshop-eksctl $ kubectl logs mnist-training -f
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-labels-idx1-ubyte.gz
32768/29515 [=================================] - 0s 0us/step
40960/29515 [=========================================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-images-idx3-ubyte.gz
26427392/26421880 [==============================] - 0s 0us/step
26435584/26421880 [==============================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-labels-idx1-ubyte.gz
16384/5148 [===============================================================================================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-images-idx3-ubyte.gz
4423680/4422102 [==============================] - 0s 0us/step
4431872/4422102 [==============================] - 0s 0us/step
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-11-30 17:41:39.513658: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-11-30 17:41:39.535677: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2019-11-30 17:41:39.535889: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x4c865d0 executing computations on platform Host. Devices:
2019-11-30 17:41:39.535910: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-11-30 17:41:39.582285: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /root//.aws/config and using profilePrefix = 1
2019-11-30 17:41:39.582325: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing config loader against fileName /root//.aws/credentials and using profilePrefix = 0
2019-11-30 17:41:39.582338: I tensorflow/core/platform/s3/aws_logging.cc:54] Setting provider to read credentials from /root//.aws/credentials for credentials file and /root//.aws/config for the config file , for use with profile default
2019-11-30 17:41:39.582351: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating HttpClient with max connections2 and scheme http
2019-11-30 17:41:39.582367: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 2
2019-11-30 17:41:39.582381: I tensorflow/core/platform/s3/aws_logging.cc:54] Creating Instance with default EC2MetadataClient and refresh rate 900000
2019-11-30 17:41:39.582416: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.582584: I tensorflow/core/platform/s3/aws_logging.cc:54] Initializing CurlHandleContainer with size 25
2019-11-30 17:41:39.582649: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.582794: I tensorflow/core/platform/s3/aws_logging.cc:54] Pool grown by 2
2019-11-30 17:41:39.582808: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-11-30 17:41:39.597911: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 400
2019-11-30 17:41:39.597954: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019-11-30 17:41:39.598078: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.598209: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-11-30 17:41:39.609385: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 400
2019-11-30 17:41:39.609421: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019-11-30 17:41:39.609534: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.609630: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-11-30 17:41:39.620537: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 400
2019-11-30 17:41:39.620572: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019-11-30 17:41:39.620625: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.620719: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-11-30 17:41:39.632697: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 400
2019-11-30 17:41:39.632730: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019-11-30 17:41:39.632781: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.632884: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-11-30 17:41:39.644034: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 400
2019-11-30 17:41:39.644065: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019-11-30 17:41:39.644116: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.644209: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-11-30 17:41:39.655145: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 400
2019-11-30 17:41:39.655177: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2019-11-30 17:41:39.655225: I tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key
2019-11-30 17:41:39.655326: I tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2019-11-30 17:41:39.666464: E tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 400
2019-11-30 17:41:39.666500: W tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
Traceback (most recent call last):
  File "mnist.py", line 89, in <module>

train_images.shape: (60000, 28, 28, 1), of float64
test_images.shape: (10000, 28, 28, 1), of float64
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
Conv1 (Conv2D)               (None, 13, 13, 8)         80        
_________________________________________________________________
flatten (Flatten)            (None, 1352)              0         
_________________________________________________________________
Softmax (Dense)              (None, 10)                13530     
=================================================================
Total params: 13,610
Trainable params: 13,610
Non-trainable params: 0
_________________________________________________________________
    main()
  File "mnist.py", line 82, in main
    model = train(train_images, train_labels, args.epochs, args.model_summary_path)
  File "mnist.py", line 51, in train
    model.fit(train_images, train_labels, epochs=epochs, callbacks=[tensorboard_callback])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_arrays.py", line 215, in model_iteration
    mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 106, in configure_callbacks
    callback_list.set_model(callback_model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 178, in set_model
    callback.set_model(model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 1010, in set_model
    self._init_writer()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 947, in _init_writer
    self.writer = tf_summary.FileWriter(self.log_dir, K.get_session().graph)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/writer.py", line 367, in __init__
    filename_suffix)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/writer/event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 442, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 458, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path), status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: : No response body. Response code: 400
workshop:~/environment/eksworkshop-eksctl $ kubectl get pods 
NAME             READY   STATUS   RESTARTS   AGE
mnist-training   0/1     Error    6          6m39s

**Comment by Jeffwan** [comment]
Can you help check it your `aws-secret` is setting correctly? 
I think you meet same problem here. 
https://github.com/aws-samples/eks-workshop/issues/542#issuecomment-557866886

**Comment by fmedery** [comment]
Closing the issue.
@ialek36 if you still have the error, don't hesitate to reopen the issue.
