### ISSUE TITLE
Sagemaker inference is failing with ClientError

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/eks-workshop#607]
Sagemaker inference from https://eksworkshop.com/advanced/420_kubeflow/pipelines/ is failing with the following error:

```
WARNING:root:pandas failed to import. Analytics features will be impaired or broken.
INFO:botocore.credentials:Found credentials in environment variables.
INFO:root:Submitting Batch Transformation request to SageMaker...
INFO:root:Batch Job request submitted. Waiting for completion...
('Created Transform job with name: ', 'BatchTransform-20191202062206-SXJC')
Transform job is still in status: InProgress
Traceback (most recent call last):
  File "batch_transform.py", line 48, in <module>
    main()
  File "batch_transform.py", line 39, in main
    _utils.print_tranformation_job_result(args.output_location)
  File "/app/common/_utils.py", line 219, in print_tranformation_job_result
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job is still in status: InProgress
Transform job ended with status: Completed
    s3_client.download_file(bucket, output_key, 'valid-result')
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python2.7/dist-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

**Comment by arun-gupta** [comment]
Duplicate of https://github.com/aws-samples/eks-workshop/issues/521

**Comment by arun-gupta** [comment]
Opening again as the endpoint is not created, unlike #521

**Comment by arun-gupta** [comment]
Endpoint needs to be picked from Sagemaker service, and then it seems to work fine
