### ISSUE TITLE
Inference won't make prediction request if you use raw training model that is copied to S3

### ISSUE THREAD

**Issue by dalbhanj** [aws-samples/eks-workshop#608]
At the very end of training chapter (https://eksworkshop.com/advanced/420_kubeflow/training/) if your mnist-training fails to run and you use raw mnist model copy to S3 using the command specified, 
aws s3 sync s3://reinvent-opn401/mnist/tf_saved_model  s3://$S3_BUCKET/mnist/tf_saved_model

the inference chapter fails with an error "requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'"

Here is the complete log,

$ python inference_client.py --endpoint http://localhost:8500/v1/models/mnist:predict
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-labels-idx1-ubyte.gz
32768/29515 [=================================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/train-images-idx3-ubyte.gz
26427392/26421880 [==============================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-labels-idx1-ubyte.gz
8192/5148 [===============================================] - 0s 0us/step
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/t10k-images-idx3-ubyte.gz
4423680/4422102 [==============================] - 0s 0us/step
Data: {"signature_name": "serving_default", "instances": ... 49], [0.027450980392156862], [0.0], [0.0], [0.0]]]]}
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/ec2-user/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_client.py", line 51, in <module>
    main()
  File "inference_client.py", line 43, in main
    json_response = requests.post(args.endpoint, data=data, headers=headers)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

**Comment by dalbhanj** [comment]
Here is the logs for mnist-inference

$ kubectl logs mnist-inference-5fd7cd57ff-8p2tp
2019-12-02 12:37:45.866088: I tensorflow_serving/model_servers/server.cc:82] Building single TensorFlow model file config:  model_name: mnist model_base_path: s3:///mnist/tf_saved_model
2019-12-02 12:37:45.866259: I tensorflow_serving/model_servers/server_core.cc:462] Adding/updating models.
2019-12-02 12:37:45.866276: I tensorflow_serving/model_servers/server_core.cc:517]  (Re-)adding model: mnist
2019-12-02 12:37:45.866438: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:46.866454: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:47.866519: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:48.866587: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:49.866656: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:50.866722: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:51.866788: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:52.866861: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:53.866930: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:54.866996: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:55.867069: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:56.867133: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:57.867200: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:58.867269: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:37:59.867336: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:00.867402: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:01.867470: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:02.867554: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:03.867610: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:04.867677: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:05.867756: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:06.867811: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:07.867877: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:08.867944: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:09.868011: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:10.868079: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:11.868159: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:12.868185: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:13.868240: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:14.868308: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:15.868376: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:16.868445: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:17.868511: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:18.868576: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:19.868643: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:20.868711: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:21.868780: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:22.868847: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:23.868915: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:24.868982: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:25.869049: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:26.869117: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:27.869182: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:28.869249: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:29.869318: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:30.869386: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:31.869453: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:32.869518: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:33.869585: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:34.869650: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:35.869715: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:36.869780: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:37.869848: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:38.869913: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:39.869978: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:40.870044: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:41.870109: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:42.870186: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:43.870243: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:44.870311: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:45.870381: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:46.870448: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:47.870513: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:48.870579: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:49.870646: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:50.870716: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:51.870781: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:52.870848: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:53.870915: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:54.870982: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:55.871052: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:56.871116: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:57.871180: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:58.871249: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:38:59.871329: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:00.871384: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:01.871453: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:02.871530: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:03.871591: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:04.871655: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:05.871719: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:06.871785: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:07.871849: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:08.871917: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:09.871981: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:10.872048: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:11.872113: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:12.872198: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:13.872248: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:14.872315: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find b se path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:15.872406: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:16.872460: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:17.872523: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:18.872590: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:19.872671: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:20.872723: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:21.872786: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:22.872852: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:23.872917: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:24.872984: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:25.873052: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:26.873121: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:27.873188: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:28.873275: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:29.873330: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:30.873393: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:31.873459: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:32.873532: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:33.873592: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:34.873675: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:35.873727: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:36.873789: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:37.873853: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:38.873916: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:39.873979: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:40.874042: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist
2019-12-02 12:39:41.874105: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3:///mnist/tf_saved_model for servable mnist

**Comment by dalbhanj** [comment]
Nevermind, I got bitten by Cloud9 not persisting S3_BUCKET env variable. After I set this env and re-deployed inference pod, I was able to get prediction without any issues

TeamRole:~/environment $ python inference_client.py --endpoint http://localhost:8500/v1/models/mnist:predict
Data: {"signature_name": "serving_default", "instances": ... 7647], [0.3843137254901961], [0.0], [0.0], [0.0]]]]}
The model thought this was a Pullover (class 2), and it was actually a Pullover (class 2)
TeamRole:~/environment $ curl -LO https://eksworkshop.com/advanced/420_kubeflow/kubeflow.files/inference_client.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1803  100  1803    0     0  27738      0 --:--:-- --:--:-- --:--:-- 27738
TeamRole:~/environment $ python inference_client.py --endpoint http://localhost:8500/v1/models/mnist:predict
Data: {"signature_name": "serving_default", "instances": ... 0.0], [0.00392156862745098], [0.0], [0.0], [0.0]]]]}
The model thought this was a T-shirt/top (class 0), and it was actually a T-shirt/top (class 0)
